#!usr/bin/env python

# enconding = utf-8

import requests
from bs4 import BeautifulSoup
import codecs

DOWNLOAD_URL = "https://map.baidu.com/?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=direct&pcevaname=pc4.1" \
               "&qt=ext&uid=0639de7acd98cf44c2f1cf77&c=288&ext_ver=new&tn=B_NORMAL_MAP&nn=0&ie=utf-8&l=15&t=1543979919568"


def download_page(url):
    data = requests.get(url).content
    return data
'''
def parse_html(html):
    soup = BeautifulSoup(html, "html.parser")
    move_list_soup = soup.find('ol', attrs={'class': 'grid_view'})

    #print(move_list_soup)

    movie_name_list = []

    for movie_li in move_list_soup.find_all('li'):
        detail = movie_li.find('div', attrs={'class': 'hd'})
        movie_name = detail.find('span', attrs={'class': 'title'}).getText()

        movie_name_list.append(movie_name)

    next_page = soup.find('span', attrs={'class': 'next'}).find('a')
    if next_page:
        return movie_name_list, DOWNLOAD_URL + next_page['href']

    return movie_name_list, None
'''


def main():
    url = DOWNLOAD_URL
    """
    with codecs.open('movies','wb',encoding='utf-8') as fp:
    while url:
        html = download_page(url)
        movies,url = parse_html(html)
        fp.write(u'{movies}\n'.format(movies='\n'.join(movies)))
    """
    print (download_page(DOWNLOAD_URL))
if __name__ == '__main__':
    main()